name: Manually Deploy to Heroku

on: workflow_dispatch

jobs:

  deploy:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2

      - uses: akhileshns/heroku-deploy@v3.12.12

        with:

          heroku_api_key: bc34229e-2021-4474-82d4-68638ff0db5d

          heroku_app_name: thikhai1yeh

          heroku_email: texovob245@paldept.com

          usedocker: true

          docker_heroku_process_type: web

          stack: "container"

          region: "eu"

